<a href="https://colab.research.google.com/github/dhivyamohan92/NumPy-and-Pandas-Data-Analysis/blob/main/perform_structured_data_analysis_using_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Create a 1D NumPy array named temperatures_w1 for Week 1 with the following
values:

In [7]:
!pip install numpy
import numpy as np
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("shape:",temperatures_w1.shape)
print("dtype:",temperatures_w1.dtype)
print("size:",temperatures_w1.size)
print("dimension:",temperatures_w1.ndim)

Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
shape: (7,)
dtype: float64
size: 7
dimension: 1

#Array operations

In [15]:
Temp_Fahrenheit=(temperatures_w1 * 9/5) + 32
print(Temp_Fahrenheit)
print("Mean_Temp:",np.mean(Temp_Fahrenheit))
print("Min_Temp:",np.min(Temp_Fahrenheit))
print("Max_Temp:",np.max(Temp_Fahrenheit))

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Mean_Temp: 74.37714285714286
Min_Temp: 69.44
Max_Temp: 78.98

Array Slicing and Indexing:

In [24]:
print("1st 3 days temp:",Temp_Fahrenheit[0:3])
print("last 2 days temp:",Temp_Fahrenheit[-2:])
print("Middle 3 days temp:",Temp_Fahrenheit[2:5])

1st 3 days temp: [72.5  77.54 69.44]
last 2 days temp: [76.64 71.42]
Middle 3 days temp: [69.44 74.12 78.98]

2D NUMPY Array

In [32]:
temperatures_2d=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures_2d)
print("shape:",temperatures_2d.shape)
print("dtype:",temperatures_2d.dtype)
print("size:",temperatures_2d.size)
print("dimension:",temperatures_2d.ndim)
print("Week1 : ",temperatures_2d[0])
print("Week2 : ",temperatures_2d[1])
print("Week1 last 2 days : ",temperatures_2d[0][-2:])
print("Week2 last 2 days : ",temperatures_2d[1][-2:])

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]
shape: (2, 7)
dtype: float64
size: 14
dimension: 2
Week1 :  [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week2 :  [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Week1 last 2 days :  [24.8 21.9]
Week2 last 2 days :  [22.8 20.1]

#Pandas

In [38]:
!pip install pandas
import pandas as pd
transactions = pd.DataFrame({"TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
"ProductCategory": ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',

'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
"Region": ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South',
'North'],
"Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})
print(transactions)
print("head:")
print(transactions.head)
print("tail:")
print(transactions.tail)
print("shape:")
print(transactions.shape)
print("Columns:")
print(transactions.columns)
print("dtypes:")
print(transactions.dtypes)

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
head:
<bound method NDFrame.head of    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400>
tail:
<bound method NDFrame.tail of    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400>
shape:
(10, 4)
Columns:
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
dtypes:
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [43]:
print("Productcategory:\n",transactions["ProductCategory"],"Amounts\n",transactions["Amount"])

Productcategory:
 0    Electronics
1       Clothing
2    Electronics
3      Furniture
4       Clothing
5    Electronics
6      Furniture
7       Clothing
8      Furniture
9    Electronics
Name: ProductCategory, dtype: object Amounts
 0    200
1    150
2    300
3    450
4    200
5    250
6    300
7    180
8    350
9    400
Name: Amount, dtype: int64

In [48]:
print("Last 3 items:\n",transactions.loc[:,["ProductCategory","Region","Amount"]])

Last 3 items:
   ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [51]:
print("Last 3 items:\n",transactions.iloc[:,-3:])

Last 3 items:
   ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [53]:
print(transactions[(transactions["Amount"]>200)&(transactions["Region"]=="North")])

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [60]:
print(transactions["ProductCategory"].value_counts())
print("Region_Unique:\n",transactions["Region"].unique())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64
Region_Unique:
 ['North' 'South' 'East' 'West']

In [65]:
print(transactions.groupby("Region")["Amount"].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [73]:
print(transactions)
transactions.loc[transactions["TransactionID"]==102,"Amount"]=165

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [92]:
transactions["Discount"] = transactions["Amount"]*10/100
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [80]:
transactions.drop(transactions[transactions["TransactionID"]==109].index,axis=0,inplace=True)
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [93]:
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [94]:
del transactions["Discount"]

In [95]:
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

Pandas Series

In [102]:
import pandas as pd
marks = pd.Series([95, 92, 89, 85, 80],index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [117]:
print("1st rank mark:",marks[0])
print("1st 3 marks:using loc\n",marks.loc[["Rank1","Rank2","Rank3"]])
print("1st 3 marks using iloc:\n",marks.iloc[:2])
mask = marks > 90
print(marks[mask])

1st rank mark: 95
1st 3 marks:using loc
 Rank1    95
Rank2    92
Rank3    89
dtype: int64
1st 3 marks using iloc:
 Rank1    95
Rank2    92
dtype: int64
Rank1    95
Rank2    92
dtype: int64

/tmp/ipykernel_2842/3111535189.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("1st rank mark:",marks[0])

In [124]:
marks["Rank1"]= 100
marks
marks.drop("Rank5")
CGPA= marks/10
print(CGPA)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Rank5     8.0
dtype: float64